<?php

/* 
 BUCLE WHILE:ESTRUCTURA DE CONTROL QUE ITERA O REPITE LA EJECUCIÓN DE UNA SERIE DE INSTRUCCIONES
 * QUE CONTIENE DENTRO Y SE REPETIRAN ESAS INSTRUCCIONES MIENTRAS QUE LA CONDICIÓN PRINCIPAL DEL 
 * BUCLE SE CUMPLA
 */


    

